# 1st Example 
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: deployment-spc-k8s-secrets
spec:
  provider: aws
  parameters:
    objects: |
      - objectName: "secret-store"
        objectType: "secretsmanager"
        jmesPath:
          - path: username
            objectAlias: dbusername
  secretObjects:
    - secretName: "secret-store"
      type: Opaque
      data:
        - objectName: dbusername
          key: db_username_01

---

# 2nd Example 
apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: myapp-aws-secrets
  namespace: 12-example
spec:
  provider: aws
  parameters:
    region: us-east-2
    objects: |
      - objectName: staging/myapp-secret-v4
        objectType: secretsmanager
        jmesPath:
            - path: username
              objectAlias: myusername
            - path: password
              objectAlias: mypassword
  secretObjects:
    - secretName: myapp-k8s-secret
      type: Opaque
      data:
        - objectName: myusername
          key: k8s-myusername
        - objectName: mypassword
          key: k8s-mypassword